### ISSUE TITLE
ONSET_DATE definition

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#1]
A network has asked for clarification on the ONSET_DATE definition. Although the spec distinguishes it from REPORT_DATE, the differences are not described.

This issue was previously opened in the [CDM Errata](https://github.com/CDMFORUM/CDM-ERRATA/issues/9), but is being merged into guidance here.

**Comment by rusincovitch** [comment]
Per discussion with the CONDITION interest group on 2016-02-26, an updated guidance is:

In the CONDITION domain, the onset date concept can be understood as “the date and time when problem (illness, disorder, or symptom) started” (ONC:MU Clinical Data Set, caDSR 4973971). This is a different concept than report date, which is the date on which the medical status was collected. 

An onset date should generally be considered independently of the observer or provider. For example, in the process of reviewing a medical history on January 1, 2016, a provider might record a condition of diabetes as onset date of March 1, 2014 (based on medical history), and report date of January 1, 2016 (the date when the condition was reported to the provider).

(Please note that this guidance is not an official addendum to the Common Data Model specification; instead, it's part of the CDM Forum’s support of implementation efforts by data partners through suggestions, recommendations, and sharing of best practices.)

**Comment by dckc** [comment]
This looks done, to me. Is there some reason not to close it? Is there a following step in some process?

**Comment by rusincovitch** [comment]
Hi @dckc: I actually hope to close this out soon with the v3.1 draft specification, which will go out for its PCORnet community feedback cycle October 3-14 [(reference)](https://github.com/CDMFORUM/CDM-GUIDANCE/blob/master/2016-08-19%20PCORnet%20CDM%20Forum%20slides.pdf), so not too much longer!

**Comment by dckc** [comment]
Ah. I see. Thanks.

**Comment by rusincovitch** [comment]
This item has been incorporated into the draft v3.1 CDM specification, with PCORnet-wide open feedback cycle opening October 3-14, 2016.
