### ISSUE TITLE
Patient address geo-related data elements

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#10]
As discussed in several venues recently, interest exists for geographic-related data elements based upon patient address.

Notes:
- This topic may include: patient textual address, specific x/y coordinate of a geocoded address, and/or geographic unit, such as block group level
- Many elements of geographic data are personally-identifiable data ([reference](https://privacyruleandresearch.nih.gov/pr_08.asp))
- Because patient addresses change over time, temporality is an important dimension
- Geo data are often associated with socio-economic status variables

**Comment by rusincovitch** [comment]
For more information, please see the entry on [Guidance for Potential CDM Enhancements](https://github.com/PCORnet/DataCommittee/wiki/Guidance-for-Potential-CDM-Enhancements) in the PCORnet Data Committee wiki.

**Comment by smerek** [comment]
Supplemental tables created.  See issue #49.
