### ISSUE TITLE
Geo-related socio-economic status (SES) data

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#11]
Interest exists in neighborhoods and/or community socio-economic status (SES) data elements. This topic is related to entry #10 because the patient address generally forms an associative link to external data sources such as the US Census, American Community Survey, business-related data domains, or proximity calculations.

Reference:
- "A number of domains of special relevance to the social determinants of health can be characterized by use of the patient's residential address...The exponential growth of geocoded data sets will likely allow linkage to a large set of potentially useful variables in coming years.“ (IOM 2014 report, ["Capturing Social and Behavioral Domains in Electronic Health Records: Phase 1," page 70](http://www.iom.edu/Reports/2014/Capturing-Social-and-Behavioral-Domains-in-Electronic-Health-Records-Phase-1.aspx))

**Comment by rusincovitch** [comment]
For more information, please see the entry on [Guidance for Potential CDM Enhancements](https://github.com/PCORnet/DataCommittee/wiki/Guidance-for-Potential-CDM-Enhancements) in the PCORnet Data Committee wiki.

**Comment by dckc** [comment]
FYI, GPC has made considerable progress on this, though mostly for i2b2:

 - [GPC: #140 socio-economic status based on geographic context](https://informatics.gpcnetwork.org/trac/Project/ticket/140)

In particular, note geocoding work with the UMN population center and [ETL by MU / Cerner](https://informatics.gpcnetwork.org/trac/Project/ticket/509).

**Comment by puroj** [comment]
ADVANCE includes Community Vital Signs geospacial data in our Research Data Warehouse, which is connected to our CDM. Detailed information can be found in Appendix B of our ADVANCE Data Dictionary: 
[ADVANCE CDM User Manual and Data Dictionary v3 2017-04-10.pdf](https://github.com/CDMFORUM/CDM-GUIDANCE/files/1064301/ADVANCE.CDM.User.Manual.and.Data.Dictionary.v3.2017-04-10.pdf)

**Comment by kmarsolo** [comment]
Cleaning up old issues.  This can be supported using the LDS_ADDRESS_HISTORY table for zip/county level measures and derived locally for more granular measures.
