### ISSUE TITLE
INSURANCE/PAYER Categories

### ISSUE THREAD

**Issue by daniellameeker** [CDMFORUM/CDM-GUIDANCE#14]
On May 21, 2016, at 8:06 AM, Rothman, Russell russell.rothman@Vanderbilt.Edu wrote:

> Do we have any plans to add insurance type (ex. Medicare vs Medicaid vs Private vs Uninsured) to the CDM?
> We have had several recent requests for this data element for studies at our CDRN.
> Thanks

Other models for reference:
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:payer_plan_period

One note - we spent a some amount of time trying to model benefit design in OMOP CDM V4. The CMS Part D data model is the most comprehensive reference for drug benefits that I've seen.  Because formularies are encoded in EHRs, we should be able to find that information more easily than other benefits.  

Considerations:
1. Service encounters and drug claims may have multiple payers (e.g. Medi-Medi duals)
2. Need to represent categories of public plans beyond Medicare and Medicaid (e.g. county, city)
3. May be of value to have not just payer but also plan ID, as in ACOs.
4. Consider value of plan type category, not just payer type (HMO, PPO, ACO, etc.)
5. Unique identifiers for payers and plans will facilitate claims integration and mapping to categories

**Comment by rusincovitch** [comment]
There may also be some potential cross-over with #3.

**Comment by smerek** [comment]
PRIMARY_INSURANCE_TYPE field added to DEMOGRAPHIC table in CDM v4.0.
