### ISSUE TITLE
Physician Clinical Service common data element for trial recruitment.

### ISSUE THREAD

**Issue by rwaitman** [CDMFORUM/CDM-GUIDANCE#17]
Supporting ADAPTABLE and the Vasculitis PPRN TAPIR trial highlight the need for clinical service of physicians to enhance clinician engagement as well as observation studies.  

One possible standard source might be the University Health System Consortium definititions for clinical specialty though there are likely others (AAMC, CMS).

**Comment by smerek** [comment]
The new PROVIDER table in CDM v4.0 includes the field PROVIDER_PRIMARY_SPECIALTY.

The value set for this data element is a modified version of the American Board of Medical Specialties (ABMS) Specialty and Subspecialty Certificates list.
