### ISSUE TITLE
Multiple DRG values possible for an encounter

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#21]
Merged from https://github.com/CDMFORUM/CDM-ERRATA/issues/15

@baileych commented on Jul 12:

It appears that, for better or worse, some health systems in PEDSnet assign more than one DRG value to a given admission (e.g. using different methods). However, it's only possible to insert one value into a row as defined by the primary key (patid, admit_date, providerid, enc_type). How would you like to handle this? I'm guessing that the benefit derived from multiple DRG values is less than the burden of duplicating rows, so for now we're choosing one value and discarding the other(s).

Thanks!

**Comment by rusincovitch** [comment]
@baileych: thank you for opening this item!

I'd suggest that your approach appears to be very compatible with both the CDM specification and current implementation guidance. 

I'm tagging this with the "potential guidance topic" label to suggest that it be considered for the CDM Implementation Guidance documentation.

**Comment by smerek** [comment]
Added to IG in CDM v4.0.
