### ISSUE TITLE
Provider entry of medical history and CONDITION table

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#24]
As suggested by @rhessmd: Provider-entered medical history can be an important source for the CONDITION table. 

She writes:
Depending on how EHR is used by providers, problem can be something historic (e.g., mastectomy or breast cancer) and/or ongoing (migraine, back pain). Past medical history would be less likely to be used for symptoms (e.g., back pain) but should contain a list of historic diagnoses (e.g., Heart Attack). It does not even mention past surgical history (and you can document hysterectomy for example in any of those 3 places).

**Comment by smerek** [comment]
The information described is included in the scope of the CONDITION table: 
CONDITION Domain Description: 
A condition represents a patient’s diagnosed and self-reported health conditions and diseases. The patient’s medical history and current state may both be represented.
