### ISSUE TITLE
What if - refactor VITAL table to allow a growing number of vital types

### ISSUE THREAD

**Issue by indera** [CDMFORUM/CDM-GUIDANCE#25]
The current structure of the VITAL table is rigid, it does not allow to collect data such as body temperature, head circumference, pulse rate, oxygen saturation, respiration rate, pain level and only allows to store the following types of data:

HT,
WT,
DIASTOLIC,
SYSTOLIC,
ORIGINAL_BMI,
SMOKING,
TOBACCO,
TOBACCO_TYPE

What would be the disadvantages or impacts on existing databases if the table is redefined to be more flexible and use just three columns to accommodate any further needs for storing data?

One possibility would be to have something similar to the LAB_RESULT_TABLE:

VITAL_TYPE - a string identifying the category of data (HT, WT, ... OXYGEN_SATURATION...)
VITAL_VALUE - a numeric value
VITAL_VALUE_UNITS - the units of the measurement

---

Another possible approach to address the need for storing details about a measurement would be to add a JSON column, given that the most popular database systems started to support JSON:

https://dev.mysql.com/doc/refman/5.7/en/json.html
https://www.postgresql.org/docs/9.3/static/functions-json.html
https://msdn.microsoft.com/en-us/library/dn921897.aspx

**Comment by rusincovitch** [comment]
Hi @indera - thank you for your thoughts!

The VITAL table does continue to be an area of assessment for new measures. The current v3.1 under development is a minor increment, but here's the [guidance on potential CDM enhancements](https://github.com/PCORnet/DataCommittee/wiki/Guidance-for-Potential-CDM-Enhancements).

My personal comments would be: An entity-attribute-value (EAV) structuring, as you describe, is often a useful construct for a strategy that optimizes storage. However, the PCORnet CDM is primarily optimized for distributed analysis modules. The efficiency and performance of distributed analytics on top of this structure has been an integral consideration. The optimization for distributed analysis modules also has driven the strong-typed data elements that are currently present in the CDM.

But this is an ongoing area of assessment! Thank you for bringing this to the forefront.

**Comment by indera** [comment]
@rusincovitch Thank you Shelley, I agree that the "how I plan to query the data" can influence to some degree the "how I store the data", but I don't expect mature analysis software to depend too much on how data is stored in the database, but I might bee too optimistic :) 

From what I am seeing only a small percentage of rows has more than 2 variables present -- most of the incoming data has (HT + WT),  (SYSTOLIC + DIASTOLIC) or SMOKING.
However the "analysis" piece seems more concerned about what data is already available and how to parse it efficiently instead of allowing expansion, which makes sense.

**Comment by smerek** [comment]
New OBS_CLIN table added in CDM v4.0.
