### ISSUE TITLE
PRESCRIBING table RX_QUANTITY - a RAW_RX_QUANTITY column could help

### ISSUE THREAD

**Issue by astoddard** [CDMFORUM/CDM-GUIDANCE#27]
In our source system for medication orders the quantity is captured as a rather unconstrained text field. 

This raises some challenges with making best use of the strictly numeric RX_QUANTITY field in the PRESCRIBING table in the 3.0 spec.

i) There is no defined place for specifying the units of the quantity. (Examples from our source data include "200 tablets", "0.5 ml", "1 inhaler").

ii) The semantics for the quantity may need to be inferred - especially for liquid drugs, different orders may indicate a volumetric dosage or a total volume to be dispensed within the source "quantity" field.

Back tracking these issues would be helped by having a RAW_RX_QUANTITY field. In our internal implementation we are considering adding a RAW_RX_QUANTITY column and hiding it if it is considered out-of-spec.

Although version 3.1 of the spec will not demand new columns would a relaxation to optionally allow additional RAW columns be with scope?

**Comment by rusincovitch** [comment]
@astoddard, thank you for bringing this up!

You would be fully in compliance with the CDM to add additional RAW fields, such as RAW_RX_QUANTITY or any others that might be helpful to you. As stated in CDM guiding principle 8: "CDRNs and PPRNs may include additional domains and data elements in localized versions of the PCORnet CDM.” (page 9 of the [CDM v3.0 specification](http://www.pcornet.org/pcornet-common-data-model/)) - thank you for considering the optimal way to implement with your source data!

Because this table is strongly based in RxNorm, the dose and units are embedded in the RxCUI which is quite granular. (For a slightly meandering conversation on this topic, please see #4).

Does this help?

**Comment by astoddard** [comment]
As best I understand it RxNorm units quantify "dosage" per discrete medication entity (at the SCD level), this is intuitive for tablet type medications, less so for liquids and gels. Units of quantity on a medication order, may or may not directly correspond to the dosage units (and may also differ from the number of dosages even for tablets - if for example the medication is dispensed in 10 mg tablets but the prescribed dose is 2 tablets at a time for 20 mg). Thus it becomes meaningful to know, even for the most straight forward case of SCD by mouth tablets, if the unit of measurement for a "RX_QUANTITY" is "doses" or "tablets".  

The ambiguity arises mostly with liquid medications given that our prescribing system doesn't make best use of RxNorm at time of writing, and isn't careful to specify how quantity is used.

Some examples: 
RXCUI 607295 - Dapsone 0.05 MG/MG Topical Gel 
Our source quantity - "60 g"

RXCUI 804183 - 0.5 ML Measles Virus Vaccine Live, Enders' attenuated Edmonston strain 2000 UNT/ML / Mumps Virus Vaccine Live, Jeryl Lynn Strain 25000 UNT/ML / Rubella Virus Vaccine Live (Wistar RA 27-3 Strain) 2000 UNT/ML Injection

Our source quantity "0.5 ml"   (Quantity without units becomes ambiguous, a different record, or the same SCD from a different datamart, might have quantity "1 dose"). Granted this is a pedantic example because it is a vaccine but hopefully it illustrates the issue with injectables.

RXCUI 1049621 - Oxycodone Hydrochloride 5 MG Oral Tablet
Our source quantity "30 tablet" 
But even inferring a quantity unit of "tablet" does not capture if the patient is instructed to take one or more tablets at a time.

**Comment by rusincovitch** [comment]
@astoddard, thank you for such a great description - this is extremely helpful to understand what you're working with and having these details laid out! I'm looking forward to discussing with the internal team early next week, and perhaps you'll be able to join us for the CDM Forum on Wednesday, November 2?

**Comment by rusincovitch** [comment]
A RAW_RX_QUANTITY field has been included in the v3.1 release, and there are other related minor tweaks to the table. @astoddard, thank you again for laying out this out so clearly!
