### ISSUE TITLE
Guidance requested for RX_FREQUENCY mapping in PRESCRIBING table

### ISSUE THREAD

**Issue by astoddard** [CDMFORUM/CDM-GUIDANCE#28]
Our source data currently includes a lot of frequencies like "3 times a day (PRN)".

The 3.0 spec has a single PRN allowed value for RX_FREQUENCY which is mutually exclusive with other frequency values. Within this scheme is it expected that all orders which include a PRN element to frequency are mapped to PRN (code 09) in a lossy manner?

(This potential loss is mitigated by the availability of the RAW_RX_FREQUENCY field which we will use to capture the source frequency value.)

Is a PRN flag as a separate column orthogonal to a frequency field in consideration for a future enhancement of the spec?

**Comment by rusincovitch** [comment]
@astoddard, thank you for your question!

This sounds like a tricky mapping. Perhaps I'm interpreting this incorrectly, but it seems like this instruction would primarily reference the PRN basis (when necessary/as needed) with a secondary aspect of 3 times a day...**when and if** it was taken by the patient.

In this situation, my suggestion would be to map to 09=As needed (PRN). However, you know your source data better than I ever can!

Capturing additional dimensions of instructions to the patient (such the additional instruction of 3 times a day) has been a topic identified for the common data model before, and I expect that it will be an area of assessment with the [strategy for Potential CDM Enhancements](https://github.com/PCORnet/DataCommittee/wiki/Guidance-for-Potential-CDM-Enhancements). 

However, in the short term, I might reference the CDM guiding principle 8: "CDRNs and PPRNs may include additional domains and data elements in localized versions of the PCORnet CDM.” (page 9 of the [CDM v3.0 specification](http://www.pcornet.org/pcornet-common-data-model/)) - this might be an option to consider if you're concerned about lossy mapping, especially if your source data are particularly well structured in this domain?

**Comment by smerek** [comment]
Implementation guidance added in CDM v4.0.

**Comment by astoddard** [comment]
I'm looking in 2017-10-01 PCORnet Common Data Model v4 0-with IG_DRAFT.pdf and not seeing any new guidance for RX_FREQUENCY. I may just be missing it.

IS_PRN as a boolean flag in an additional separate column would still be my suggestion for CDM4.0.  That doesn't preclude PRN as a member of the RX_FREQUENCY value set but would allow direct capturing of orders like TID PRN without massively expanding the value set.

**Comment by smerek** [comment]
Hi Alex.
This is the implementation guidance I just added to the draft v4.0 spec (which is why you don't see it in the released version):

"For source values that specify PRN plus additional information (e.g., “PRN, 3 times a day”) select 09=As needed (PRN) and store source value in RAW_RX_FREQUENCY field (guidance added in v4.0)."

Thanks for keeping up with this.
~Michelle

**Comment by astoddard** [comment]
Ah, thank you Michelle.

Just good (bad?) timing on my part then. I happen to be back working on Medication relation stuff and reviewing CDM4.0 right now and github helpfully sent me the notification of change on my old issue.

Sorry for jumping the gun. At least it proves someone cares and issue tracking is genuinely appreciated (-:


Thanks again,
Alex Stoddard
Programmer/Analyst Biomedical Informatics
Clinical & Translational Science Institute
Medical College of Wisconsin
astoddard@mcw.edu (414) 805-7239
--------------------------------------------------
UL1 TR001436, TL1 TR001437, KL2 TR001438
CITE it - You can ensure our resources are
          available for all future research.
          Simply cite the NIH CTSA.

**Comment by smerek** [comment]
Good timing!  It's so nice to know I'm not just talking to myself here.  :~)
