### ISSUE TITLE
RESULT_MODIFIER: clarify when to use TX in the CDM v3.1 document

### ISSUE THREAD

**Issue by indera** [CDMFORUM/CDM-GUIDANCE#29]
The definition of RESULT_MODIFIER on page 49 of CDM v3.0 states: 

> Modifier for result values. Any symbols in the RAW_RESULT value should be reflected in the RESULT_MODIFIER variable.
> For example, if the original source data value is "<=200" then RAW_RESULT=200 and RESULT_MODIFIER=LE. If the original source data value is text then RESULT_MODIFIER=TX. If the original source data value is a numeric value then RESULT_MODIFIER=EQ.

I think two problems need to be addressed:

1. Add back the definition for RESULT_MODIFIER to page 49 of the CDM v3.1 document.
2. Clarify if it is correct to translate "If the original source data value is text..." as "If the result is qualitative then RESULT_MODIFIER = TX"?

The reason RESULT_MODIFIER is difficult to populate is that the ETL code needs to "look" at three potential "sources of truth" to determine the proper value:
 
- result_qualifier_source_value
- result_num_source_value
- result_modifier_source_value

**Comment by smerek** [comment]
Thank you for your great comments and questions.

For CDM v3.1 the implementation guidance that was previously included in the "Definition/Comments" field in CDM v3.0 has been incorporated into its own Implementation Guidance document.  It's posted on iMeetCentral here: https://pcornet.imeetcentral.com/p/aQAAAAAC4Zr4

Based on this guidance for populating RESULT_MODIFIER (page 17): "If the original source data value is text, then RESULT_MODIFIER=TX" I would say your interpretation is correct!

**Comment by indera** [comment]
@smerek
Michelle, 
Thank you for the prompt answer.
