### ISSUE TITLE
Dose field for the PRESCRIBING Table

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#30]
@rwaitman recommends adding a dose field to the PRESCRIBING table to compliment the RxNorm mappings (for example, where RxNorm mapping at high granularity is not possible).

**Comment by rwaitman** [comment]
Examples are 
- when you order 90 mg of enoxaparin that will be drawn from a 100 mg/ml prefilled syringe.
- kids take most drugs as liquids and the RXCUI will just be at the level of the vial or bottle
- you're ordering chemotherapy which will be dispensed as an IV piggyback and the dosage is very important but unlikely to ever be at an explicit RXCUI level  (eg doxorubicin /m2)

Reference the fact that OMOP has an effective dose field in the DRUG_EXPOSURE table and i2b2 also would allow storage of the dose as a numeric.
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:drug_exposure

**Comment by smerek** [comment]
Ordered and Calculated strength fields added to PRESCRIBING table in CDM v4.0.
