### ISSUE TITLE
ENC_TYPE must be defined as `non_null` in the DIAGNOSIS and PROCEDURES tables

### ISSUE THREAD

**Issue by indera** [CDMFORUM/CDM-GUIDANCE#33]
During data characterization, replication error(s) in ENC_TYPE in the DIAGNOSIS or PROCEDURES table are flagged with red color, which means that they must be fixed.

Most of the time I find that the ENC_TYPE is just set to `NULL` in the  DIAGNOSIS or PROCEDURES  tables while it is not null in the corresponding ENCOUNTER row.

I think the CDM model needs to be changed to say that ENC_TYPE should not allow NULL values in the DIAGNOSIS or PROCEDURES tables to prevent replication issues.

**Comment by smerek** [comment]
Implementation guidance added in v4.0.
