### ISSUE TITLE
PRO_CM table

### ISSUE THREAD

**Issue by kmarsolo** [CDMFORUM/CDM-GUIDANCE#37]
CDM spec says Common Measure table is included in the Implementation Guidance.  It's still part of the CDM spec.

**Comment by smerek** [comment]
Hi.  Are you referring to the LAB_RESULT Common Measure table?  That table was removed from the CDM specification, effective version 3.1.

**Comment by marey5** [comment]
It's the PRO_LOINC field definition.  The CDM spec says that the LOINC codes for each common measure are in the Implementation Guidance, but the PRO Common Measures table is still part of the CDM spec. 

Keith

**Comment by rusincovitch** [comment]
@marey5, it sounds like this is an important next step for the PRO table! I'm going to go ahead and tag this with both implementation guidance and CDM enhancement.

**Comment by smerek** [comment]
Addressed in CDM v4.0.
