### ISSUE TITLE
Notes storage in observation table

### ISSUE THREAD

**Issue by rwaitman** [CDMFORUM/CDM-GUIDANCE#38]
As discussed at the Data Committee face to face meetings (Sept 2016 and March 2017), having the optional capability for sites to put notes data into an observation table that can be linked to a concept table would allow the network to conduct cross network NLP.  

While it may not be tractable for a network site to load "all their notes" in this form, having the optional ability to do so, even if for a specific cohort study would be very desirable.

Related topics on notes storage are:
1.  Need to define procedures for how and when this capability is used or discoverable.
2.  Storage as well of the title (and possibly using HL7 domain elements to standardize note types: progress note, radiology, pathology, patient instructions).
3.  Storage of the note author or type of author which will in many cases not be the provider for the encounter
4.  Downstream storage of NLP products and structured output.  In i2b2, this might be as additional observations organized by concepts while OHDSI community has other best practices in representing different forms of NLP output.

**Comment by smerek** [comment]
Two observation tables (OBS_CLIN and OBS_GEN) added in CDM v4.0.
