### ISSUE TITLE
List of provider specialities

### ISSUE THREAD

**Issue by kmarsolo** [CDMFORUM/CDM-GUIDANCE#48]
Attaching a list of provider specialties currently used by PEDSnet in their internal CDM, which is based on OMOP.
[Provider_Specialty.xlsx](https://github.com/CDMFORUM/CDM-GUIDANCE/files/1232198/Provider_Specialty.xlsx)

**Comment by smerek** [comment]
Provider specialty incorporated into CDM v4.0
