### ISSUE TITLE
Draft specification for Linkage / Geocoding Supplemental tables

### ISSUE THREAD

**Issue by kmarsolo** [CDMFORUM/CDM-GUIDANCE#49]
Draft specification for Supplemental tables to store PHI commonly used in geocoding / patient linkage algorithms, as well as metadata about the algorithms themselves.
[Supplemental_Tables-2017_09_29.docx](https://github.com/CDMFORUM/CDM-GUIDANCE/files/1347463/Supplemental_Tables-2017_09_29.docx)

**Comment by indera** [comment]
Without knowing too much about the goal of the table, the current version of the document indicates that for the **LINKAGE_INFO** table the primary key is the combination of : PATID, LINKID,TRIALID,PARTICIPANTID,CONFIDENCE. However, the not-null constraint is only for the PATID and LINKID columns. In my opinion the PK should be changed to only consist of the two non-null columns and a separate "unique" constraint added for the combination. Alternatively, if the intent is to permit multiple rows having the same combination PATID+LINKID, then we probably want to change the TRIALID,PARTICIPANTID,CONFIDENCE columns to require "not-null" values.

**Comment by indera** [comment]
Another option would be to have the PK consist of PATID, LINKID, LINK_TYPE, LINK_CONFIDENCE (all required values) and move the mapping between a LINKID->(PATID,TRIALID,PARTICIPANTID) to a dedicated table. This approach has the advantage that it makes it easier to reason about the goal of the table, but again this is just an "uninformed" opinion.

**Comment by kmarsolo** [comment]
Tables being populated by pSCANNER.
