### ISSUE TITLE
RXNORM_CUI definition

### ISSUE THREAD

**Issue by smerek** [CDMFORUM/CDM-GUIDANCE#5]
The RxCUI term-type list ("ordered strategy") in the Definition/Comments column for the RXNORM_CUI field in the PRESCRIBING table is not an exhaustive list of the only RxCUI term-types that could be included in this field.  It is intended to be a mapping guide for the case where there is more than one RxCUI per medication record.

**Comment by rusincovitch** [comment]
This item has been incorporated into draft v3.0 Implementation Guidance, part of the PCORnet-wide open feedback cycle on Data Characterization (September 19-30, 2016): [https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb](https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb)

**Comment by rbrad8158** [comment]
The updated guidance allows us to include more options of RXNORM CUI however there remains a potential issue of there being multiple RxNorm codes of the same term type. For example, an internal medication code for "FUROSEMIDE 10 MG/ML INJECTION SOLUTION" may be mapped to 4 potentially different Semantic Clinical Drug RxNorm Codes: 

1719286 - 10 ML Furosemide 10 MG/ML Injection
1719290 - 2 ML Furosemide 10 MG/ML Injection
1719291 - 4 ML Furosemide 10 MG/ML Injection
1719287 - [Has been quantified and is remapped to multiple concepts] (additional issue of previously used RxNorm that are now deprecated/remapped and if they should still be supported)

At the PRESCRIBING level it's not necessarily possible to determine which sized vial would be used without digging down to what dispensing or administration information may be available for that order. Digging that far would (generally) only be obtainable for inpatient medications.

If there is a class at a more 'preferred' term type, should we drill down until we find an RxNorm code that has a 1:1 cardinality with the internal medication id? In the above case, this  might be all the way at the Ingredient level (4603 - Furosemide)?

**Comment by smerek** [comment]
Thank you for this great example.  In this scenario, since you do not have information in the internal medication code that gets you to the semantic clinical drug/generic drug pack level, would it make sense to map to the RxCUI at the level of information you have easy(ish) access to -- the semantic clinical drug component level:
![image](https://cloud.githubusercontent.com/assets/8716701/20193506/4931126e-a75c-11e6-9c8f-138e45253f93.png)

That way, you are mapping to the RxCUI at the highest level of specificity that corresponds to the source data.
