### ISSUE TITLE
? incorrect link

### ISSUE THREAD

**Issue by schillil** [CDMFORUM/CDM-GUIDANCE#6]
"pSCANNER lab mapping process: Link to document" - this "link to document' doesn't appear to link to a pSCANNER document. Thanks

**Comment by smerek** [comment]
Hi!  GitHub does not like MS Word very much...

Did you try clicking the "Raw" tab or the "View Raw" link?  That opens the .doc for me but I am curious to know if that works for you!

**Comment by smerek** [comment]
Created a .pdf file and corrected the link.  Thanks to schillil for pointing this out!
