### ISSUE TITLE
Value Set Reference Dose Form has Unprintable Characters

### ISSUE THREAD

**Issue by don-torok** [CDMFORUM/CDM-GUIDANCE#74]
ValueSet_ReferenceFile_v1.2.xlsx; Tab: RX_DOSE_FORM 
Some entries have a trailing unprintable character, octal 160.  In Excel ORAL_TABLET appears to have a trailing space.  But if you dump the tab into a text file and look with a hex editor you will see the trailing value is octal 160.  We loaded the database from the text file and this value got propagated into the database. This caused the error 'Required fields contain values outside of data model specifications' in the PCORnet4 characterization report.  ORAL_TABLET is not the only value with this problem.

**Comment by smerek** [comment]
Hello Don.  Thank you for reporting this issue.  There were several issues of this nature with the value set reference file, so a corrected file (PCORnet Common Data Model Value Set Reference File v1.3) was posted on May 15th.  Please find it here: http://pcornet.org/pcornet-common-data-model/

**Comment by don-torok** [comment]
I just looked at PCORnet_CDM_ValueSet_ReferenceFile_v1.3.xlsx the problem
with space and underscores between words has been correct, BUT there is
still a problem with unprintable character at the end of some strings.
Look at RX_DOSE_FORM ORAL_TABLET.  There is what looks like a space after
ORAL_TABLET.  Export the tab to a text file and then look at with a hex
editor and you will see that rather than a space the character is hex A0
(umlaut lower case a).

**Comment by kmarsolo** [comment]
Don - you are correct.  Some of those characters appear in the Preferred Language value set.  Here's the updated version.  We're working to push the update to the pcornet.org page.
[PCORnet_CDM_ValueSet_ReferenceFile_v1.4.xlsx](https://github.com/CDMFORUM/CDM-GUIDANCE/files/2017046/PCORnet_CDM_ValueSet_ReferenceFile_v1.4.xlsx)

**Comment by kmarsolo** [comment]
Fixed in v1.4 (released May 18).
