### ISSUE TITLE
parseable spreadsheet for 4.1?

### ISSUE THREAD

**Issue by dckc** [CDMFORUM/CDM-GUIDANCE#84]
Where did it go?

The 4.1 spec says

> Note to programmers: The separate “CDM parseable file” is more helpful for direct use in implementation, and contains the complete table specifications. All documentation is available here:
http://www.pcornet.org/pcornet-common-data-model/

but that link is broken now.

**Comment by kmarsolo** [comment]
The PCORnet website was revamped, which broke all the links.  The CDM documents can be found here: https://pcornet.org/data-driven-common-model/ (scroll to bottom)

We are working to get everything updated.
